// flow-typed signature: bded219bfe1e564866800814f4c882b9
// flow-typed version: <<STUB>>/babel-plugin-dotenv-import_v^1.3.1/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-dotenv-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-dotenv-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-dotenv-import/test/fixtures/as-alias/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/test/fixtures/blacklist/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/test/fixtures/custom-module/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/test/fixtures/default-import/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/test/fixtures/default/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/test/fixtures/filename/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/test/fixtures/from-env/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/test/fixtures/safe-error/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/test/fixtures/safe-success/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/test/fixtures/undefined/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/test/fixtures/unused/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/test/fixtures/variable-not-exist/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/test/fixtures/whitelist/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/test/fixtures/wildcard-import/source' {
  declare module.exports: any;
}

declare module 'babel-plugin-dotenv-import/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-dotenv-import/index' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import'>;
}
declare module 'babel-plugin-dotenv-import/index.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import'>;
}
declare module 'babel-plugin-dotenv-import/test/fixtures/as-alias/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/test/fixtures/as-alias/source'>;
}
declare module 'babel-plugin-dotenv-import/test/fixtures/blacklist/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/test/fixtures/blacklist/source'>;
}
declare module 'babel-plugin-dotenv-import/test/fixtures/custom-module/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/test/fixtures/custom-module/source'>;
}
declare module 'babel-plugin-dotenv-import/test/fixtures/default-import/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/test/fixtures/default-import/source'>;
}
declare module 'babel-plugin-dotenv-import/test/fixtures/default/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/test/fixtures/default/source'>;
}
declare module 'babel-plugin-dotenv-import/test/fixtures/filename/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/test/fixtures/filename/source'>;
}
declare module 'babel-plugin-dotenv-import/test/fixtures/from-env/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/test/fixtures/from-env/source'>;
}
declare module 'babel-plugin-dotenv-import/test/fixtures/safe-error/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/test/fixtures/safe-error/source'>;
}
declare module 'babel-plugin-dotenv-import/test/fixtures/safe-success/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/test/fixtures/safe-success/source'>;
}
declare module 'babel-plugin-dotenv-import/test/fixtures/undefined/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/test/fixtures/undefined/source'>;
}
declare module 'babel-plugin-dotenv-import/test/fixtures/unused/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/test/fixtures/unused/source'>;
}
declare module 'babel-plugin-dotenv-import/test/fixtures/variable-not-exist/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/test/fixtures/variable-not-exist/source'>;
}
declare module 'babel-plugin-dotenv-import/test/fixtures/whitelist/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/test/fixtures/whitelist/source'>;
}
declare module 'babel-plugin-dotenv-import/test/fixtures/wildcard-import/source.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/test/fixtures/wildcard-import/source'>;
}
declare module 'babel-plugin-dotenv-import/test/test.js' {
  declare module.exports: $Exports<'babel-plugin-dotenv-import/test/test'>;
}
