// flow-typed signature: e981d68233819bc1cc7dbff96d9b795c
// flow-typed version: <<STUB>>/react-native-scalable-image_v^0.4.0/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-scalable-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-scalable-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-scalable-image/index' {
  declare module.exports: $Exports<'react-native-scalable-image'>;
}
declare module 'react-native-scalable-image/index.js' {
  declare module.exports: $Exports<'react-native-scalable-image'>;
}
