// flow-typed signature: fdde4025e1ca7955b2272e278f17c48a
// flow-typed version: <<STUB>>/react-native-dash_v^0.0.8/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-dash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-dash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-dash/Dash' {
  declare module.exports: any;
}

declare module 'react-native-dash/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-dash/Dash.js' {
  declare module.exports: $Exports<'react-native-dash/Dash'>;
}
declare module 'react-native-dash/util.js' {
  declare module.exports: $Exports<'react-native-dash/util'>;
}
