// flow-typed signature: f4dd839f843fe23c4977844c40392c87
// flow-typed version: <<STUB>>/react-native-maps-directions_v^1.6.0/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-maps-directions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-maps-directions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-maps-directions/src/MapViewDirections' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-maps-directions/index' {
  declare module.exports: $Exports<'react-native-maps-directions'>;
}
declare module 'react-native-maps-directions/index.js' {
  declare module.exports: $Exports<'react-native-maps-directions'>;
}
declare module 'react-native-maps-directions/src/MapViewDirections.js' {
  declare module.exports: $Exports<'react-native-maps-directions/src/MapViewDirections'>;
}
