# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  lane :certs do
    match(
      type: "development"
    )
    match(
      type: "adhoc",
      force_for_new_devices: true
    )
  end

  lane :beta do
    register_devices(
      devices_file: "./devices.txt"
    )
    match(
      type: "adhoc",
      force_for_new_devices: true
    )
    # increment_build_number
    # commit_version_bump(
    #   message: "Bump build number"
    # )
    build_app(
      scheme: "RegioJet Release",
      workspace: "RegioJet.xcworkspace",
      include_bitcode: true
    )
    crashlytics(
      api_token: ENV["CRASHLYTICS_API_TOKEN"],
      build_secret: ENV["CRASHLYTICS_BUILD_SECRET"]
    )
    slack(
      slack_url: ENV["SLACK_URL"],
      message: "iOS app successfully built!"
    )
  end
end
