# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :beta do
    gradle(
      task: "assemble",
      build_type: "Release"
    )
    crashlytics(
      api_token: ENV["CRASHLYTICS_API_TOKEN"],
      build_secret: ENV["CRASHLYTICS_BUILD_SECRET"]
    )
    slack(
      slack_url: ENV["SLACK_URL"],
      message: "Android app successfully built!"
    )
  end

  # lane :playstore do
  #   upload_to_play_store(
  #     track: 'internal',
  #     apk: 'app/build/outputs/apk/release/app-release.apk'
  #   )
  # end
end
